"""
Grok Aurora API Client - Playwright Browser Bridge Edition
Uses a real Chromium browser (with injected cookies) to make requests,
so the Statsig SDK inside the page generates a valid x-statsig-id header.
"""

import asyncio
import json
import os
import tempfile
from typing import Optional, AsyncGenerator, List
from playwright.async_api import async_playwright, Browser, BrowserContext, Page


class GrokClient:
    """
    Grok Aurora client using Playwright browser bridge.
    
    Because Grok requires x-statsig-id (generated by the Statsig SDK running
    inside the browser), we can't forge it in plain HTTP requests.
    Instead, we launch a headless Chromium, inject the user's cookies, navigate
    to grok.com, and execute fetch() calls from within the page context.
    """

    GROK_URL = "https://grok.com"
    IMAGE_GEN_URL = "https://grok.com/rest/app-chat/conversations/new"

    def __init__(self, cookies: Optional[dict] = None):
        self.cookies = cookies or {}
        self._playwright = None
        self._browser: Optional[Browser] = None
        self._context: Optional[BrowserContext] = None
        self._page: Optional[Page] = None

    async def __aenter__(self):
        await self._start_browser()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        await self._stop_browser()

    async def _start_browser(self):
        """Launch headless Chromium and inject cookies."""
        self._playwright = await async_playwright().start()
        self._browser = await self._playwright.chromium.launch(
            headless=True,
            args=[
                "--no-sandbox",
                "--disable-setuid-sandbox",
                "--disable-dev-shm-usage",
                "--disable-blink-features=AutomationControlled",
            ]
        )
        self._context = await self._browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/131.0.0.0 Safari/537.36"
            ),
            viewport={"width": 1280, "height": 800},
        )

        # Inject cookies into the browser context
        if self.cookies:
            playwright_cookies = []
            for name, value in self.cookies.items():
                if name in ("sso", "sso-rw", "cf_clearance", "__cf_bm",
                            "i18nextLng", "x-userid", "last-logged-in-with",
                            "referrer", "OptanonConsent",
                            "mp_0b4055a12491884bcb6f34a5aa2718b6_mixpanel",
                            "mp_ea93da913ddb66b6372b89d97b1029ac_mixpanel"):
                    playwright_cookies.append({
                        "name": name,
                        "value": value,
                        "domain": ".grok.com",
                        "path": "/",
                        "secure": True,
                        "httpOnly": name in ("sso", "sso-rw"),
                        "sameSite": "Lax",
                    })
            if playwright_cookies:
                await self._context.add_cookies(playwright_cookies)

        self._page = await self._context.new_page()

        # Navigate to grok.com so the Statsig SDK initialises
        try:
            await self._page.goto(self.GROK_URL, wait_until="domcontentloaded", timeout=30000)
            # Give Statsig SDK a moment to initialise
            await asyncio.sleep(2)
        except Exception:
            # Even if navigation fails, we can still make fetch() calls
            pass

    async def _stop_browser(self):
        """Clean up browser resources."""
        if self._page:
            await self._page.close()
        if self._context:
            await self._context.close()
        if self._browser:
            await self._browser.close()
        if self._playwright:
            await self._playwright.stop()

    async def _fetch_sse(self, payload: dict, timeout_ms: int = 300000) -> AsyncGenerator[dict, None]:
        """
        Execute a fetch() call inside the browser page and stream the SSE response.
        Yields parsed JSON objects from each SSE data line.
        """
        if not self._page:
            raise RuntimeError("Browser not started. Use 'async with' context manager.")

        # We use a JS helper that reads the SSE stream and returns all chunks
        js_code = """
        async (url, payload) => {
            const resp = await fetch(url, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload),
                credentials: 'include',
            });
            const status = resp.status;
            if (!resp.ok) {
                const text = await resp.text();
                return { error: true, status, text: text.slice(0, 500) };
            }
            const reader = resp.body.getReader();
            const decoder = new TextDecoder();
            const chunks = [];
            let buffer = '';
            while (true) {
                const { done, value } = await reader.read();
                if (done) break;
                buffer += decoder.decode(value, { stream: true });
                const lines = buffer.split('\\n');
                buffer = lines.pop();
                for (const line of lines) {
                    if (line.startsWith('data: ')) {
                        const data = line.slice(6).trim();
                        if (data && data !== '[DONE]') {
                            chunks.push(data);
                        }
                    }
                }
            }
            return { error: false, status, chunks };
        }
        """

        result = await self._page.evaluate(
            js_code,
            [self.IMAGE_GEN_URL, payload]
        )

        if result.get("error"):
            yield {
                "status": "error",
                "code": result.get("status"),
                "message": result.get("text", "Unknown error")
            }
            return

        for chunk in result.get("chunks", []):
            try:
                data = json.loads(chunk)
                yield {"status": "generating", "data": data}
            except json.JSONDecodeError:
                pass

        yield {"status": "done"}

    async def generate_image(
        self,
        prompt: str,
        aspect_ratio: str = "1:1",
        quality: str = "standard"
    ) -> AsyncGenerator[str, None]:
        """
        Generate image using Grok Aurora via browser bridge.
        Yields JSON strings with generation progress/results.
        """
        payload = {
            "temporary": True,
            "modelName": "aurora",
            "message": prompt,
            "imageGenerationConfig": {
                "aspectRatio": aspect_ratio,
                "quality": quality,
                "n": 1,
            }
        }

        image_urls = []
        try:
            async for event in self._fetch_sse(payload):
                if event.get("status") == "error":
                    yield json.dumps(event)
                    return

                if event.get("status") == "generating":
                    data = event.get("data", {})
                    # Extract image URLs from the response
                    self._extract_image_urls(data, image_urls)
                    yield json.dumps({"status": "generating", "data": data})

                elif event.get("status") == "done":
                    yield json.dumps({
                        "status": "complete",
                        "images": image_urls
                    })

        except Exception as e:
            yield json.dumps({"status": "error", "message": str(e)})

    def _extract_image_urls(self, data: dict, image_urls: list):
        """Recursively extract image URLs from SSE response data."""
        if isinstance(data, dict):
            # Check for direct image URL fields
            for key in ("imageUrl", "url", "image_url"):
                if key in data and isinstance(data[key], str) and data[key].startswith("http"):
                    if data[key] not in image_urls:
                        image_urls.append(data[key])
            # Check for assets.grok.com URLs in any string value
            for val in data.values():
                if isinstance(val, str) and "assets.grok.com" in val:
                    if val not in image_urls:
                        image_urls.append(val)
                elif isinstance(val, (dict, list)):
                    self._extract_image_urls(val, image_urls)
        elif isinstance(data, list):
            for item in data:
                self._extract_image_urls(item, image_urls)

    async def generate_video(
        self,
        prompt: str,
        duration: int = 6,
        aspect_ratio: str = "16:9",
        resolution: str = "480p"
    ) -> AsyncGenerator[str, None]:
        """
        Generate video using Grok Aurora via browser bridge.
        Yields JSON strings with generation progress/results.
        """
        payload = {
            "temporary": True,
            "modelName": "aurora",
            "message": prompt,
            "videoGenerationConfig": {
                "aspectRatio": aspect_ratio,
                "videoLength": duration,
                "resolutionName": resolution,
                "isVideoEdit": False,
            }
        }

        video_url = None
        try:
            async for event in self._fetch_sse(payload, timeout_ms=600000):
                if event.get("status") == "error":
                    yield json.dumps(event)
                    return

                if event.get("status") == "generating":
                    data = event.get("data", {})
                    # Extract video URL
                    video_url = self._extract_video_url(data) or video_url
                    yield json.dumps({"status": "generating", "data": data})

                elif event.get("status") == "done":
                    yield json.dumps({
                        "status": "complete",
                        "video": video_url
                    })

        except Exception as e:
            yield json.dumps({"status": "error", "message": str(e)})

    def _extract_video_url(self, data) -> Optional[str]:
        """Recursively extract video URL from SSE response data."""
        if isinstance(data, dict):
            for key in ("videoUrl", "url", "video_url"):
                if key in data and isinstance(data[key], str) and data[key].startswith("http"):
                    return data[key]
            for val in data.values():
                if isinstance(val, str) and ("assets.grok.com" in val or ".mp4" in val):
                    return val
                elif isinstance(val, (dict, list)):
                    result = self._extract_video_url(val)
                    if result:
                        return result
        elif isinstance(data, list):
            for item in data:
                result = self._extract_video_url(item)
                if result:
                    return result
        return None
